# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c893c9304e76945a3ff97f2642e2028507f3098c00b61f9a70181e8884c70fd8353baac5499c79824a7320d8906d46c490e5efe51e8ee75502e08170d395bdcd

test:
  secret_key_base: 3210aa923cd168a263a45d15a75b6db60620ab58d3e442b0ff5ab1f2c3db706541529f2912015007cf9b4fa7bea44d151b5e002b1e459f133bcb73eefc291df3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
